import "./globals.css"
import type { Metadata } from "next"
import { Raleway } from "next/font/google"
import AuthProvider from "../components/AuthProvider"
import ReactQueryProvider from "../components/ReactQueryProvider"

const raleway = Raleway({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <AuthProvider>
          <body className={raleway.className} suppressHydrationWarning={true}>
            <div className="flex min-h-screen flex-col">{children}</div>
          </body>
        </AuthProvider>
      </html>
    </ReactQueryProvider>
  )
}
